{{- if and .Values.mattermost.enabled .Values.mattermost.webhookUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mattermost.secretName | quote }}
  namespace: {{ include "monitoring-extras.namespace" . }}
type: Opaque
stringData:
  url: {{ .Values.mattermost.webhookUrl | quote }}
{{- end }}
