apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: admin-gateway-envoy-prom
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: istio
spec:
  namespaceSelector:
    matchNames:
      - istio-admin-gateway
  selector:
    matchLabels:
      istio: admin-ingressgateway
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
      scrapeTimeout: 10s
      scheme: http
