apiVersion: v1
kind: Secret
metadata:
  name: mattermost-webhook
  namespace: monitoring
type: Opaque
stringData:
  # Incoming webhook URL (Mattermost): https://chat.<domain>/hooks/<token>
  url: "###ZARF_VAR_MATTERMOST_WEBHOOK_URL###"
